spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MyPJDB
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG