spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MyPJDB
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG

jwt:
  secret: iGj2i-j0ku-XCRTyOAWyQATsqvHRP3ePGan6e9YvQR8WSyLoS8MpWw2ojvhgMx8qTsXWMs-DGJiSs2vKQhHBqA
  expiration: 604800000 # 예: 1주일